### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by pddring** [JJTB100/HydroHeat#1]
We need a logo for HydroHeat

**Comment by pddring** [comment]
We could do with a colour scheme too: can we use https://coolors.co/

**Comment by pddring** [comment]
![image](https://user-images.githubusercontent.com/760604/217245815-eacf2268-67b7-4eb1-99dd-dcb36ef3da9e.png)

**Comment by pddring** [comment]
https://coolors.co/363020-605c4e-124e78-8ee3ef-f4743b

**Comment by JJTB100** [comment]
![palet](https://user-images.githubusercontent.com/99484954/217274058-fc22c626-a7bf-42d3-a4d0-c4badfd4c67a.png)

**Comment by JJTB100** [comment]
Updated so that there's more grey and less brown.

**Comment by JJTB100** [comment]
![colorsUpdated](https://user-images.githubusercontent.com/99484954/217521209-095a6c7d-2787-485d-b897-a1ac045913d9.png)
These colours are slightly edited so they fit better together
